# -*- coding: utf-8 -*-
"""Agente_Cocina_IA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KyD4SszFhBiIp4Jr2nQAP0aRb46qb-1l

# 🍳 Agente de Cocina con IA (Gemini + PDF)

Este notebook crea un asistente que lee un PDF con recetas y responde tus preguntas
sobre ellas (explicar una receta, sugerir sustitutos de ingredientes, adaptar cantidades, etc.)

## 1. Instalamos dependencias
"""

!pip install -q -U google-genai gradio pypdf
print("Listo ✅")

"""## 2. Subimps el PDF de recetas

Al correr esta celda, se observará un botón para elegir el archivo desde la computadora.
"""

from google.colab import files

print("Selecciona tu PDF de recetas...")
uploaded = files.upload()
pdf_filename = list(uploaded.keys())[0]
print(f"\n✅ Archivo subido: {pdf_filename}")

"""## 3. Extraer el texto del PDF"""

from pypdf import PdfReader

reader = PdfReader(pdf_filename)
recetas_texto = ""

for i, pagina in enumerate(reader.pages):
    texto_pagina = pagina.extract_text() or ""
    recetas_texto += f"\n--- Página {i+1} ---\n{texto_pagina}"

print(f"✅ Se extrajeron {len(reader.pages)} páginas.")
print(f"Total de caracteres: {len(recetas_texto)}")
print("\nVista previa del contenido extraído:\n")
print(recetas_texto[:800])

"""> ⚠️ Si la "vista previa" salió vacía o con símbolos raros, es porque tu PDF
> es un PDF escaneado (imágenes) y no texto real. En ese caso avísame y usamos
> otra técnica (OCR) para extraerlo.

## 4. Configuramos la API Key de Gemini
"""

from google.colab import userdata
from google import genai

GEMINI_API_KEY = userdata.get("GEMINI_API_KEY")
client = genai.Client(api_key=GEMINI_API_KEY)

MODEL = "gemini-2.5-flash"

# Prueba rápida para confirmar que la key funciona
test = client.models.generate_content(model=MODEL, contents="Responde solo con: conexión exitosa")
print(test.text)

"""## 5. Definimos el "cerebro" del agente

Aquí le decimos a Gemini que es un chef experto y le damos el contenido del PDF como su única fuente de recetas.
"""

INSTRUCCIONES_SISTEMA = f"""Eres un asistente de cocina experto y amigable.
Tu única fuente de recetas es el siguiente documento (extraído de un PDF).
Cuando el usuario pregunte por una receta, ingredientes, pasos, tiempos de cocción,
sustitutos de ingredientes o cantidades, básate SIEMPRE en este documento.

Si el usuario pide algo que no está en el documento, dilo claramente y ofrece
la receta más parecida que sí encuentres ahí.

Explica los pasos de forma clara y ordenada, como si le hablaras a alguien
que recién está aprendiendo a cocinar.

--- CONTENIDO DEL PDF DE RECETAS ---
{recetas_texto}
--- FIN DEL CONTENIDO ---
"""

print(f"Instrucciones del sistema listas ({len(INSTRUCCIONES_SISTEMA)} caracteres).")

"""## 6. Función de chat (conecta Gradio con Gemini)"""

from google.genai import types

def extraer_texto(contenido):
    """
    Convierte el 'content' de un mensaje de Gradio a texto plano,
    sin importar si viene como string simple o como lista de fragmentos.
    """
    if isinstance(contenido, str):
        return contenido
    if isinstance(contenido, list):
        partes = []
        for fragmento in contenido:
            if isinstance(fragmento, dict) and "text" in fragmento:
                partes.append(fragmento["text"])
            elif isinstance(fragmento, str):
                partes.append(fragmento)
        return " ".join(partes)
    return str(contenido)


def chatear_con_agente(mensaje, historial):
    """
    mensaje: texto que escribió el usuario ahora
    historial: lista de turnos anteriores que arma Gradio automáticamente
    """
    contenidos = []

    for turno in historial:
        rol = turno.get("role")
        texto = extraer_texto(turno.get("content", ""))
        if not texto:
            continue
        if rol == "user":
            contenidos.append(types.Content(role="user", parts=[types.Part(text=texto)]))
        elif rol == "assistant":
            contenidos.append(types.Content(role="model", parts=[types.Part(text=texto)]))

    contenidos.append(types.Content(role="user", parts=[types.Part(text=extraer_texto(mensaje))]))

    respuesta = client.models.generate_content(
        model=MODEL,
        contents=contenidos,
        config=types.GenerateContentConfig(
            system_instruction=INSTRUCCIONES_SISTEMA,
            temperature=0.4,
        ),
    )

    return respuesta.text

print("Función de chat lista ✅")

"""## 7. Lanzar la interfaz de chat 🚀"""

import gradio as gr

demo = gr.ChatInterface(
    fn=chatear_con_agente,
    title="🍳 Chef IA - Tu asistente de recetas",
    description="Pregúntame sobre cualquier receta del PDF que subiste: ingredientes, pasos, tiempos, sustitutos, etc.",
    examples=[
        "¿Qué recetas tienes disponibles?",
        "Explícame paso a paso la primera receta",
        "¿Con qué puedo reemplazar la mantequilla?",
    ],
)

demo.launch(debug=True)